### ISSUE TITLE
Can not parse messages with ipv6 originating source

### ISSUE THREAD

**Issue by tschiemer** [martim01/sapserver#1]
Heheja there!

I'm working on something similar (AES67 related) so just happened to browse your code when I noticed that your parser does not seem to consider ipv6 originating sources both when reading out the ip and further on considering the space used (by the ip)

https://github.com/martim01/sapserver/blob/f2bf763981724d5cc5efbd9d3361c0b791f09a0c/src/parser.cpp#L28

https://github.com/martim01/sapserver/blob/f2bf763981724d5cc5efbd9d3361c0b791f09a0c/src/parser.cpp#L35

**Comment by MatthewMartinBBC** [comment]
You're correct - I'd completely forgotten about adding it. I've now updated the code to take the IPv6 in to account also decode the data in to a human readable string .

**Comment by martim01** [comment]
You're correct, I'd forgotten that I'd left this to do at another time.
I've now updated the code to handle IPv6 and also decode the data to a human readable string.
Thanks for pointing this out

**Comment by tschiemer** [comment]
👍 

Just to mention as I noticed also... any (theoretical) authentication data will come after the originating source and before payload data, ie. `+ 4 * aMessage.nAuthenticationLength`
